input_stream: "REQUEST_PAYLOAD:input"
output_stream: "RESPONSE_PAYLOAD:output"
node {
  name: "RerankExecutor"
  input_side_packet: "RERANK_NODE_RESOURCES:rerank_servable"
  calculator: "RerankCalculatorOV"
  input_stream: "REQUEST_PAYLOAD:input"
  output_stream: "RESPONSE_PAYLOAD:output"
  node_options: {
    [type.googleapis.com / mediapipe.RerankCalculatorOVOptions]: {
      models_path: "C:\\Users\\someo\\agentic-tool-loop\\services\\launch\\models-ovms-rerank\\BAAI\\bge-reranker-v2-m3",
      plugin_config: '{"NUM_STREAMS": "1" }',
      target_device: "CPU"
    }
  }
}
